site_name: AD - Acc茅s a Dades - Ficheros

extra_css:
  - css/extra.css
  - img/favicon.ico 

theme: 
  name: readthedocs
  features:
    - navigation.expand
    - navigation.sections
    - navigation.tabs
    - copy-to-clipboard
    - content.code.copy
  #highlightjs: true
  logo: assets/logocaminas.png
    

#extra_javascript:
#  - js/extra.js


markdown_extensions:
  - admonition
  - tables    
  - attr_list
  - toc

nav:
- Introducci贸n: 
  - RA_CE.md
  - IntelliJ: Idea.md
  - Kotlin: Kotlin.md  
- Sistema de ficheros:
  -  Ficheros: AD_T1_Sistema_de_fitxers/ficheros.md
  -  Acceso al sistema de ficheros. Java.nio: AD_T1_Sistema_de_fitxers/NIO_AccesoFicheros.md
  - Exercicis: AD_T1_Sistema_de_fitxers/exercicis.md
- Manejo de ficheros:
    - Formas de acceso a un fichero: AD_T2_Gesti_del_contingut_de_fitxers/Formas_acceso.md
    - Clases y m茅todos sobre ficheros. Java.nio: AD_T2_Gesti_del_contingut_de_fitxers/clases.md
    - Lectura y escritura de ficheros: 
      - Ficheros de texto y binarios: AD_T2_Gesti_del_contingut_de_fitxers/Lectura_Escritura_ficheros.md
      - Ficheros de imagen: AD_T2_Gesti_del_contingut_de_fitxers/ficheros_img.md
      - Ficheros binarios estructurados: AD_T2_Gesti_del_contingut_de_fitxers/binarios_estucturados.md  
      - Ficheros de acceso aleatorio: AD_T2_Gesti_del_contingut_de_fitxers/Acceso_aleatorio.md
- Ficheros con formatos diferentes:
    - Introducci贸n: AD_T3_Fitxers_de_diferents_formats/objectius.md
    - Serializaci贸n de Objetos: AD_T3_Fitxers_de_diferents_formats/seriaci_dobjectes.md
    - Ficheros de intercambio: AD_T3_Fitxers_de_diferents_formats/ficheros_intercambio.md    
    - Exercicis: AD_T3_Fitxers_de_diferents_formats/exercicis.md
- Conversi贸n entre formatos diferentes: Conversion.md
# - Programaci贸n de componentes: Componentes.md    
- Resumen: 
    - Tipos de ficheros: Resumen_tipos.md    
       
