site_name: AD - Acceso a Datos - Ficheros

extra_css:
  - css/extra.css
  - img/favicon.ico 
  - css/copy-button.css

extra_javascript:
  - js/copy-button.js  

theme: 
  name: readthedocs
  features:
    - navigation.expand
    - navigation.sections
    - navigation.tabs
    - copy-to-clipboard
    - content.code.copy
  logo: assets/logocaminas.png
    


markdown_extensions:
  - admonition
  - tables    
  - attr_list
  - toc
  - md_in_html

nav:

- RA y CE: RA_CE.md
- Sistema de ficheros:
  - ğŸ”¹ Ficheros: T1_Sistema_de_ficheros/ficheros.md
  - ğŸ”¹ Acceso al sistema de ficheros. Java.nio: T1_Sistema_de_ficheros/NIO_AccesoFicheros.md
  - ğŸ“ Ejercicio obligatorio 1: T1_Sistema_de_ficheros/exercicis.md
- Manejo de ficheros:
    - ğŸ”¹Formas de acceso a un fichero: T2_Gestion_del_contenido/Formas_acceso.md
    - ğŸ”¹Clases y mÃ©todos sobre ficheros. Java.nio: T2_Gestion_del_contenido/clases.md
    - ğŸ”¹Lectura y escritura de ficheros: T2_Gestion_del_contenido/Lectura_Escritura_ficheros.md
- Ficheros de diferentes formatos :
    - ğŸ”¹IntroducciÃ³n: T3_Formatos_diferentes/intro.md
    - ğŸ”¹SerializaciÃ³n de Objetos: T3_Formatos_diferentes/seriaci_dobjectes.md
    - ğŸ”¹Ficheros de intercambio: T3_Formatos_diferentes/ficheros_intercambio.md    
    - ğŸ”¹ConversiÃ³n entre formatos diferentes: T3_Formatos_diferentes/Conversion.md
    - ğŸ“ Ejercicio obligatorio 2: T3_Formatos_diferentes/ejercicios.md
- Resumen: Resumen.md       
